version: '3.8'
services:
    nginx:
        image: nginx:1.15
        ports:
            - "80:80"
        volumes:
            - ./source:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    php-fpm:
        build:  ./docker/php-fpm
        volumes:
            - ./laravel:/var/www/html
    composer:
        container_name: composer
        image: composer:latest
        volumes:
            - ./laravel:/app
        entrypoint: composer
    mysql:
        image: mysql:5.7
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: laravel_sample_db
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: laravel_sample_user
            MYSQL_PASSWORD: password
            TZ: Asia/Tokyo
        ports:
            - "63306:3306"
        